---
plugins:
  - prettier
env:
  browser: true
  amd: true
  commonjs: true
  es2021: true
  node: true
ignorePatterns:
  - lib/*
  - out/*
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  prettier/prettier: error

