env:
  browser: true
  amd: true
  commonjs: true
  es2021: true
  node: true
ignorePatterns:
  - lib/*
  - out/*
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  indent: [0, 4] # TODO enable
